#!/bin/bash
sudo chmod +x fullMake
reset
echo "STARING TO BUILD THE GAME..."
echo "ENTERING THE GAME ENGINE DIRECTORY..."
cd lib/
echo "Creating lib directory if it does not exist."
mkdir "lib"
echo "Creating obj directory if it does not exist."
mkdir "obj"
echo "REMOVING .o AND .d FILES..."
sudo make clean
echo "COMPILING THE GAME ENGINE..."
sudo make install
echo "RETURNING to THE GAME DIRECTORY..."
cd ..
echo "REMOVING .o AND .d FILES..."
sudo make clean
echo "COMPILING THE GAME..."
sudo make -j8